 const  User = [
   {
      name: "Isabelle Keating",
      make: "Toyota",
      model: "Celica",
      price: 350000,
      color: "red",
      Country: "India",
      skill: "Billiards",
    },
    {
      name: "Charlotte Lopes",
      make: "Porsche",
      model: "Boxster",
      price: 702000,
      color: "pink",
      Country: "Singapore",
      skill: "BasketBall",
    },
    {
      name: "Emily Jagger",
      make: "Toyota",
      model: "Celica",
      price: 350000,
      color: "red",
      Country: "India",
      skill: "Chess",
    },
      {
      name: "Andrew Jacoby",
      make: "Ford",
      model: "Mondeo",
      price: 320000,
      color: "white",
      Country: "Japan",
      skill: "Tennis",
    },
    {
      name: "Dimple Jacoby",
      make: "Toyota",
      model: "Celica",
      price: 350000,
      color: "red",
      Country: "India",
      skill: "Football",
    },
     {
      name: "Freya Donovan",
      make: "Toyota",
      model: "Auto",
      price: 120000,
      color: "pink",
      Country: "USA",
      skill: "BasketBall",
    },
    {
      name: "Mia Hunter",
      make: "Toyota",
      model: "Celica",
      price: 350000,
      color: "red",
      Country: "India",
      skill: "Badminton",
    },
    {
      name: "Mia Smith",
      make: "Safari",
      model: "x700",
      price: 15000,
      color: "yellow",
      Country: "Japan",
      skill: "Soccer",
    },
    {
      name: "Dimple Jacoby",
      make: "Mercedes",
      model: "Creta",
      price: 120000,
      color: "blue",
      Country: "Malaysia",
      skill: "Snowboarding",
    },
]
 export default User;